query me {
  me {
    id
    display
    contact
    gender
    role {
      name
      id
    }
    createdDate
    isActive
    ownerId
    startingAt
    bankName
    bankAcc
    bankType
    position
    baseSalary
    type
    profile
    username
    fromTime
    toTime
  }
}

query productList($offset: Int, $limit: Int, $code: String, $schedule: Boolean, $filter: FilterProduct) {
  productList(offset: $offset, limit: $limit, code: $code, schedule: $schedule, filter: $filter) {
    id
    code
    title
    status
    category {
      id
      name
    }
    images
    sku {
      id
      name
      price
      status
      discount
      image
    }
    type
  }
}

query categoryList {
  categoryList
}

query settingList {
  settingList {
    value
    type
    option
  }
}

query getbankList {
  getbankList {
    id
    name
  }
}

query order($token: String, $orderId: Int) {
  order(token: $token, id: $orderId) {
    id
    address
    status
    bankId
    customerPaid
    name
    paid
    set
    total
    uuid
    note
    code
    discount
    vat
    person
    currency
    invoice
    bankType
    log {
      date
      text
      by {
        id
        display
      }
    }
    deliveryCode
    delivery {
      id
      name
      contact
    }
    items {
      createdDate
      id
      qty
      sku {
        price
        discount
        id
        unit
        name
        image
      }
      product {
        title
        images
        code
        description
        id
      }
      price
      discount
      status
      addons
      remark
      isPrint
    }
  }
}

query orderList(
  $offset: Int
  $limit: Int
  $viewBy: OrderViewBy
  $status: [StatusOrder]
  $orderId: String
  $sign: Boolean
  $discount: Boolean
  $toDate: String
  $fromDate: String
) {
  orderList(
    offset: $offset
    limit: $limit
    viewBy: $viewBy
    status: $status
    orderId: $orderId
    sign: $sign
    discount: $discount
    toDate: $toDate
    fromDate: $fromDate
  ) {
    id
    code
    deliveryCode
    discount
    delivery {
      id
      name
      contact
    }
    items {
      id
      price
      product {
        id
        images
        title
        code
      }
      qty
      discount
      addons
      remark
      sku {
        name
        image
      }
      status
      createdDate
    }
    status
    name
    paid
    set
    bankId
    currency
    total
    uuid
    note
    vat
    bankType
    invoice
    person
    log {
      date
      text
      by {
        id
        display
      }
    }
  }
}
