query me {
  me {
    id
    display
    contact
    gender
    role {
      name
      id
    }
    createdDate
    isActive
    ownerId
    startingAt
    bankName
    bankAcc
    bankType
    position
    baseSalary
    type
    profile
    username
    fromTime
    toTime
  }
}

query productList($offset: Int, $limit: Int, $code: String, $schedule: Boolean, $filter: FilterProduct) {
  productList(offset: $offset, limit: $limit, code: $code, schedule: $schedule, filter: $filter) {
    id
    code
    title
    status
    category {
      id
      name
    }
    images
    sku {
      id
      name
      price
      status
      discount
      image
    }
    type
  }
}